google_ttf: fix memset warning
The wrong sizeof() variable was being used which lead to the below warning when
LTO=none was used.

common/include/linux/fortify-string.h:242:4: error: call to
__write_overflow_field declared with 'warning' attribute: detected write beyond
size of field (1st parameter); maybe use struct_group()?
[-Werror,-Wattribute-warning]
                        __write_overflow_field(p_size_field, size);
                        ^
1 error generated.

Bug: 231318697
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ibf176d0be887a41ce4d36bb844ee5f934f0dc124