p9221_chip: add missing #include <linux/gpio/driver.h>
As of upstream kernel commit [1], this fails compilation with
    In file included from .../private/google-modules/bms/p9221_chip.c:21:
    .../private/google-modules/bms/p9221_charger.h:844:19: error: field has incomplete type 'struct gpio_chip'
            struct gpio_chip gpio;
                             ^
    .../private/google-modules/bms/p9221_charger.h:844:9: note: forward declaration of 'struct gpio_chip'
            struct gpio_chip gpio;
                   ^
    .../private/google-modules/bms/p9221_chip.c:2029:39: error: call to undeclared function 'gpiochip_get_data'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            struct p9221_charger_data *charger = gpiochip_get_data(chip);
                                                 ^
    .../private/google-modules/bms/p9221_chip.c:2029:29: error: incompatible integer to pointer conversion initializing 'struct p9221_charger_data *' with an expression of type 'int' [-Wint-conversion]
            struct p9221_charger_data *charger = gpiochip_get_data(chip);
                                       ^         ~~~~~~~~~~~~~~~~~~~~~~~
    3 errors generated.

Add the missing #include.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=21d9526d13b5467b
    ("gpiolib: Make the legacy <linux/gpio.h> consumer-only")

Bug: 283455416
Test: TH
Signed-off-by: André Draszik <andre.draszik@linaro.org>
(cherry picked from https://partner-android-review.googlesource.com/q/commit:9386fb934cd1d20639e13a9748d4741467e55e68)
Merged-In: Ie519a93acc4233a51792532fcab8228dcd28e41d
Change-Id: Ie519a93acc4233a51792532fcab8228dcd28e41d