logbuffer: do not call vprintk_emit when !CONFIG_PRINTK
If CONFIG_PRINTK is not defined then vprintk_emit will not be
defined and cause compilation errors.

bms/misc/logbuffer.c:145:2: error: implicit declaration of function
	'vprintk_emit' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Pat Tjin <pattjin@google.com>
Change-Id: Ia86901b82d9f43a6368742f1d568bacff917afb6